export const LINK_FIELDS = [
  {
    labelName: "x profile",
    fieldName: "twitter",
    placeholder: "https://x.com/username",
  },
  {
    labelName: "github",
    fieldName: "github",
    placeholder: "https://github.com/username",
  },
  {
    labelName: "linkedin",
    fieldName: "linkedin",
    placeholder: "https://linkedin.com/in/username",
  },
  {
    labelName: "website",
    fieldName: "website",
    placeholder: "https://personal-website.com",
  },
];

export const GENDER_SELECT_OPTIONS = [
  { value: "male", label: "male" },
  { value: "female", label: "female" },
  { value: "non-binary", label: "non-binary" },
  { value: "other", label: "other" },
  { value: "prefer-not-to-say", label: "prefer not to say" },
];

// ISO 3166-1 alpha-2 codes for values
// Common countries that will appear at the top of the list
export const COMMON_COUNTRIES = [
  { value: "US", label: "united states 🇺🇸" },
  { value: "CA", label: "canada 🇨🇦" },
  { value: "CN", label: "china 🇨🇳" },
  { value: "IN", label: "india 🇮🇳" },
  { value: "MX", label: "mexico 🇲🇽" },
  { value: "GB", label: "united kingdom 🇬🇧" },
  { value: "DE", label: "germany 🇩🇪" },
  { value: "FR", label: "france 🇫🇷" },
  { value: "JP", label: "japan 🇯🇵" },
  { value: "BR", label: "brazil 🇧🇷" },
  { value: "NG", label: "nigeria 🇳🇬" },
  { value: "PL", label: "poland 🇵🇱" },
  { value: "SA", label: "saudi arabia 🇸🇦" },
  { value: "AU", label: "australia 🇦🇺" },
  { value: "ES", label: "spain 🇪🇸" },
];

// All countries in alphabetical order (excluding the common ones that will be at the top)
export const ALL_COUNTRIES = [
  { value: "AF", label: "afghanistan 🇦🇫" },
  { value: "AL", label: "albania 🇦🇱" },
  { value: "DZ", label: "algeria 🇩🇿" },
  { value: "AS", label: "american samoa 🇦🇸" },
  { value: "AD", label: "andorra 🇦🇩" },
  { value: "AO", label: "angola 🇦🇴" },
  { value: "AI", label: "anguilla 🇦🇮" },
  { value: "AQ", label: "antarctica 🇦🇶" },
  { value: "AG", label: "antigua and barbuda 🇦🇬" },
  { value: "AR", label: "argentina 🇦🇷" },
  { value: "AM", label: "armenia 🇦🇲" },
  { value: "AW", label: "aruba 🇦🇼" },
  { value: "AT", label: "austria 🇦🇹" },
  { value: "AZ", label: "azerbaijan 🇦🇿" },
  { value: "BS", label: "bahamas 🇧🇸" },
  { value: "BH", label: "bahrain 🇧🇭" },
  { value: "BD", label: "bangladesh 🇧🇩" },
  { value: "BB", label: "barbados 🇧🇧" },
  { value: "BY", label: "belarus 🇧🇾" },
  { value: "BE", label: "belgium 🇧🇪" },
  { value: "BZ", label: "belize 🇧🇿" },
  { value: "BJ", label: "benin 🇧🇯" },
  { value: "BM", label: "bermuda 🇧🇲" },
  { value: "BT", label: "bhutan 🇧🇹" },
  { value: "BO", label: "bolivia 🇧🇴" },
  { value: "BA", label: "bosnia and herzegovina 🇧🇦" },
  { value: "BW", label: "botswana 🇧🇼" },
  { value: "BV", label: "bouvet island 🇧🇻" },
  { value: "IO", label: "british indian ocean territory 🇮🇴" },
  { value: "BN", label: "brunei darussalam 🇧🇳" },
  { value: "BG", label: "bulgaria 🇧🇬" },
  { value: "BF", label: "burkina faso 🇧🇫" },
  { value: "BI", label: "burundi 🇧🇮" },
  { value: "KH", label: "cambodia 🇰🇭" },
  { value: "CM", label: "cameroon 🇨🇲" },
  { value: "CV", label: "cape verde 🇨🇻" },
  { value: "KY", label: "cayman islands 🇰🇾" },
  { value: "CF", label: "central african republic 🇨🇫" },
  { value: "TD", label: "chad 🇹🇩" },
  { value: "CL", label: "chile 🇨🇱" },
  { value: "CX", label: "christmas island 🇨🇽" },
  { value: "CC", label: "cocos (keeling) islands 🇨🇨" },
  { value: "CO", label: "colombia 🇨🇴" },
  { value: "KM", label: "comoros 🇰🇲" },
  { value: "CG", label: "congo 🇨🇬" },
  { value: "CD", label: "congo, democratic republic 🇨🇩" },
  { value: "CK", label: "cook islands 🇨🇰" },
  { value: "CR", label: "costa rica 🇨🇷" },
  { value: "CI", label: "cote d'ivoire 🇨🇮" },
  { value: "HR", label: "croatia 🇭🇷" },
  { value: "CU", label: "cuba 🇨🇺" },
  { value: "CY", label: "cyprus 🇨🇾" },
  { value: "CZ", label: "czech republic 🇨🇿" },
  { value: "DK", label: "denmark 🇩🇰" },
  { value: "DJ", label: "djibouti 🇩🇯" },
  { value: "DM", label: "dominica 🇩🇲" },
  { value: "DO", label: "dominican republic 🇩🇴" },
  { value: "EC", label: "ecuador 🇪🇨" },
  { value: "EG", label: "egypt 🇪🇬" },
  { value: "SV", label: "el salvador 🇸🇻" },
  { value: "GQ", label: "equatorial guinea 🇬🇶" },
  { value: "ER", label: "eritrea 🇪🇷" },
  { value: "EE", label: "estonia 🇪🇪" },
  { value: "ET", label: "ethiopia 🇪🇹" },
  { value: "FK", label: "falkland islands (malvinas) 🇫🇰" },
  { value: "FO", label: "faroe islands 🇫🇴" },
  { value: "FJ", label: "fiji 🇫🇯" },
  { value: "FI", label: "finland 🇫🇮" },
  { value: "GF", label: "french guiana 🇬🇫" },
  { value: "PF", label: "french polynesia 🇵🇫" },
  { value: "TF", label: "french southern territories 🇹🇫" },
  { value: "GA", label: "gabon 🇬🇦" },
  { value: "GM", label: "gambia 🇬🇲" },
  { value: "GE", label: "georgia 🇬🇪" },
  { value: "GH", label: "ghana 🇬🇭" },
  { value: "GI", label: "gibraltar 🇬🇮" },
  { value: "GR", label: "greece 🇬🇷" },
  { value: "GL", label: "greenland 🇬🇱" },
  { value: "GD", label: "grenada 🇬🇩" },
  { value: "GP", label: "guadeloupe 🇬🇵" },
  { value: "GU", label: "guam 🇬🇺" },
  { value: "GT", label: "guatemala 🇬🇹" },
  { value: "GN", label: "guinea 🇬🇳" },
  { value: "GW", label: "guinea-bissau 🇬🇼" },
  { value: "GY", label: "guyana 🇬🇾" },
  { value: "HT", label: "haiti 🇭🇹" },
  { value: "HM", label: "heard island and mcdonald islands 🇭🇲" },
  { value: "VA", label: "holy see (vatican city state) 🇻🇦" },
  { value: "HN", label: "honduras 🇭🇳" },
  { value: "HK", label: "hong kong 🇭🇰" },
  { value: "HU", label: "hungary 🇭🇺" },
  { value: "IS", label: "iceland 🇮🇸" },
  { value: "ID", label: "indonesia 🇮🇩" },
  { value: "IR", label: "iran 🇮🇷" },
  { value: "IQ", label: "iraq 🇮🇶" },
  { value: "IE", label: "ireland 🇮🇪" },
  { value: "IL", label: "israel 🇮🇱" },
  { value: "IT", label: "italy 🇮🇹" },
  { value: "JM", label: "jamaica 🇯🇲" },
  { value: "JO", label: "jordan 🇯🇴" },
  { value: "KZ", label: "kazakhstan 🇰🇿" },
  { value: "KE", label: "kenya 🇰🇪" },
  { value: "KI", label: "kiribati 🇰🇮" },
  { value: "KP", label: "korea, democratic people's republic of 🇰🇵" },
  { value: "KR", label: "korea, republic of 🇰🇷" },
  { value: "KW", label: "kuwait 🇰🇼" },
  { value: "KG", label: "kyrgyzstan 🇰🇬" },
  { value: "LA", label: "lao people's democratic republic 🇱🇦" },
  { value: "LV", label: "latvia 🇱🇻" },
  { value: "LB", label: "lebanon 🇱🇧" },
  { value: "LS", label: "lesotho 🇱🇸" },
  { value: "LR", label: "liberia 🇱🇷" },
  { value: "LY", label: "libyan arab jamahiriya 🇱🇾" },
  { value: "LI", label: "liechtenstein 🇱🇮" },
  { value: "LT", label: "lithuania 🇱🇹" },
  { value: "LU", label: "luxembourg 🇱🇺" },
  { value: "MO", label: "macao 🇲🇴" },
  { value: "MK", label: "macedonia 🇲🇰" },
  { value: "MG", label: "madagascar 🇲🇬" },
  { value: "MW", label: "malawi 🇲🇼" },
  { value: "MY", label: "malaysia 🇲🇾" },
  { value: "MV", label: "maldives 🇲🇻" },
  { value: "ML", label: "mali 🇲🇱" },
  { value: "MT", label: "malta 🇲🇹" },
  { value: "MH", label: "marshall islands 🇲🇭" },
  { value: "MQ", label: "martinique 🇲🇶" },
  { value: "MR", label: "mauritania 🇲🇷" },
  { value: "MU", label: "mauritius 🇲🇺" },
  { value: "YT", label: "mayotte 🇾🇹" },
  { value: "FM", label: "micronesia 🇫🇲" },
  { value: "MD", label: "moldova 🇲🇩" },
  { value: "MC", label: "monaco 🇲🇨" },
  { value: "MN", label: "mongolia 🇲🇳" },
  { value: "MS", label: "montserrat 🇲🇸" },
  { value: "MA", label: "morocco 🇲🇦" },
  { value: "MZ", label: "mozambique 🇲🇿" },
  { value: "MM", label: "myanmar 🇲🇲" },
  { value: "NA", label: "namibia 🇳🇦" },
  { value: "NR", label: "nauru 🇳🇷" },
  { value: "NP", label: "nepal 🇳🇵" },
  { value: "NL", label: "netherlands 🇳🇱" },
  { value: "AN", label: "netherlands antilles 🇳🇱" },
  { value: "NC", label: "new caledonia 🇳🇨" },
  { value: "NZ", label: "new zealand 🇳🇿" },
  { value: "NI", label: "nicaragua 🇳🇮" },
  { value: "NE", label: "niger 🇳🇪" },
  { value: "NU", label: "niue 🇳🇺" },
  { value: "NF", label: "norfolk island 🇳🇫" },
  { value: "MP", label: "northern mariana islands 🇲🇵" },
  { value: "NO", label: "norway 🇳🇴" },
  { value: "OM", label: "oman 🇴🇲" },
  { value: "PK", label: "pakistan 🇵🇰" },
  { value: "PW", label: "palau 🇵🇼" },
  { value: "PS", label: "palestinian territory 🇵🇸" },
  { value: "PA", label: "panama 🇵🇦" },
  { value: "PG", label: "papua new guinea 🇵🇬" },
  { value: "PY", label: "paraguay 🇵🇾" },
  { value: "PE", label: "peru 🇵🇪" },
  { value: "PH", label: "philippines 🇵🇭" },
  { value: "PN", label: "pitcairn 🇵🇳" },
  { value: "PT", label: "portugal 🇵🇹" },
  { value: "PR", label: "puerto rico 🇵🇷" },
  { value: "QA", label: "qatar 🇶🇦" },
  { value: "RE", label: "reunion 🇷🇪" },
  { value: "RO", label: "romania 🇷🇴" },
  { value: "RU", label: "russian federation 🇷🇺" },
  { value: "RW", label: "rwanda 🇷🇼" },
  { value: "SH", label: "saint helena 🇸🇭" },
  { value: "KN", label: "saint kitts and nevis 🇰🇳" },
  { value: "LC", label: "saint lucia 🇱🇨" },
  { value: "PM", label: "saint pierre and miquelon 🇵🇲" },
  { value: "VC", label: "saint vincent and the grenadines 🇻🇨" },
  { value: "WS", label: "samoa 🇼🇸" },
  { value: "SM", label: "san marino 🇸🇲" },
  { value: "ST", label: "sao tome and principe 🇸🇹" },
  { value: "SN", label: "senegal 🇸🇳" },
  { value: "CS", label: "serbia and montenegro 🇷🇸" },
  { value: "SC", label: "seychelles 🇸🇨" },
  { value: "SL", label: "sierra leone 🇸🇱" },
  { value: "SG", label: "singapore 🇸🇬" },
  { value: "SK", label: "slovakia 🇸🇰" },
  { value: "SI", label: "slovenia 🇸🇮" },
  { value: "SB", label: "solomon islands 🇸🇧" },
  { value: "SO", label: "somalia 🇸🇴" },
  { value: "ZA", label: "south africa 🇿🇦" },
  { value: "GS", label: "south georgia and the south sandwich islands 🇬🇸" },
  { value: "LK", label: "sri lanka 🇱🇰" },
  { value: "SD", label: "sudan 🇸🇩" },
  { value: "SR", label: "suriname 🇸🇷" },
  { value: "SJ", label: "svalbard and jan mayen 🇸🇯" },
  { value: "SZ", label: "swaziland 🇸🇿" },
  { value: "SE", label: "sweden 🇸🇪" },
  { value: "CH", label: "switzerland 🇨🇭" },
  { value: "SY", label: "syrian arab republic 🇸🇾" },
  { value: "TW", label: "taiwan 🇹🇼" },
  { value: "TJ", label: "tajikistan 🇹🇯" },
  { value: "TZ", label: "tanzania 🇹🇿" },
  { value: "TH", label: "thailand 🇹🇭" },
  { value: "TL", label: "timor-leste 🇹🇱" },
  { value: "TG", label: "togo 🇹🇬" },
  { value: "TK", label: "tokelau 🇹🇰" },
  { value: "TO", label: "tonga 🇹🇴" },
  { value: "TT", label: "trinidad and tobago 🇹🇹" },
  { value: "TN", label: "tunisia 🇹🇳" },
  { value: "TR", label: "turkey 🇹🇷" },
  { value: "TM", label: "turkmenistan 🇹🇲" },
  { value: "TC", label: "turks and caicos islands 🇹🇨" },
  { value: "TV", label: "tuvalu 🇹🇻" },
  { value: "UG", label: "uganda 🇺🇬" },
  { value: "UA", label: "ukraine 🇺🇦" },
  { value: "AE", label: "united arab emirates 🇦🇪" },
  { value: "UM", label: "united states minor outlying islands 🇺🇲" },
  { value: "UY", label: "uruguay 🇺🇾" },
  { value: "UZ", label: "uzbekistan 🇺🇿" },
  { value: "VU", label: "vanuatu 🇻🇺" },
  { value: "VE", label: "venezuela 🇻🇪" },
  { value: "VN", label: "vietnam 🇻🇳" },
  { value: "VG", label: "virgin islands, british 🇻🇬" },
  { value: "VI", label: "virgin islands, u.s. 🇻🇮" },
  { value: "WF", label: "wallis and futuna 🇼🇫" },
  { value: "EH", label: "western sahara 🇪🇭" },
  { value: "YE", label: "yemen 🇾🇪" },
  { value: "ZM", label: "zambia 🇿🇲" },
  { value: "ZW", label: "zimbabwe 🇿🇼" },
];

// Combined list for backwards compatibility
export const COUNTRIES_SELECT_OPTIONS = [...COMMON_COUNTRIES, ...ALL_COUNTRIES];
